import { NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, businessName, category, googlePlaceId } = body;

    if (!email || !businessName) {
      return NextResponse.json(
        { success: false, error: 'Email and Business Name are required.' },
        { status: 400 }
      );
    }

    // 1. Check or create User
    let user = await prisma.user.findUnique({
      where: { email }
    });

    if (!user) {
      user = await prisma.user.create({
        data: {
          name: name || 'Business Owner',
          email,
          role: 'owner'
        }
      });
    }

    // 2. Map category to template key (must match seeded keys: restaurant, tyre_shop, salon_retail, hotel)
    const validCategories = ['restaurant', 'tyre_shop', 'salon_retail', 'hotel'];
    const templateKey = validCategories.includes(category) ? category : 'restaurant';

    // 3. Create Business (UUID will be automatically generated by PostgreSQL/Prisma)
    const business = await prisma.business.create({
      data: {
        name: businessName,
        category: templateKey as any,
        templateKey,
        googlePlaceId: googlePlaceId || 'ChIJN1t_tDeuEmsRUsoyG83VSY4',
        ownerId: user.userId
      }
    });

    // 4. Log audit log
    await prisma.auditLog.create({
      data: {
        entityType: 'businesses',
        entityId: business.businessId,
        action: 'CREATE',
        performedBy: email,
        details: {
          message: `Registered new location "${businessName}" linked to owner: ${email}`
        }
      }
    });

    return NextResponse.json({
      success: true,
      businessId: business.businessId,
      businessName: business.name,
      ownerEmail: email
    });

  } catch (error: any) {
    console.error('Registration API error:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to register business.' },
      { status: 500 }
    );
  }
}
